### ISSUE TITLE
Copytranslator 軟體問題

### ISSUE THREAD

**Issue by Miche1202** [elliottzheng/elliottzheng#1]
Hi Copytranslator Team,
想請教軟體不能運作問題...
我是Win 10 安裝 v10.0.0-beta.3 版本,
不能運作的時候：
複製Paper中的字時(pdf檔)或是word檔中的英文字,軟體會出現"翻譯完成Undefined→Undefined", 再請協助確認是甚麼東西卡住了? 謝謝
![image](https://user-images.githubusercontent.com/90435405/132800602-e8f80082-1467-4f29-8254-743055713d74.png)

**Comment by elliottzheng** [comment]
请尝试[最新版本](https://github.com/CopyTranslator/CopyTranslator/releases/tag/v10.0.0) 并反馈问题，谢谢
